
root = "."
tmp_dir = "tmp"
bin = "tmp/main"

[build]
cmd = "go build -o tmp/main ./cmd/server/main.go"
include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["air.toml"]
delay = 2000

[log]
level = "info"
color = true

[serve]
cmd = "./tmp/main"
graceful_restart = true
