services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  justdone:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: justdone
    command: sleep 100h
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pgdata:
